In [1]:
from keras.preprocessing.image import ImageDataGenerator, load_img, img_to_array, array_to_img

Using TensorFlow backend.


In [2]:
datagen = ImageDataGenerator(
        rotation_range=40,
        width_shift_range=0.2,
        height_shift_range=0.2,
        zoom_range=0.2,
        horizontal_flip=True,
        fill_mode='nearest')

In [4]:
img = load_img('butterfly.jpg')
img_array = img_to_array(img)
print(img_array)

[[[ 59.  57. 106.]
  [ 58.  54. 104.]
  [ 58.  48. 101.]
  ...
  [149. 178. 124.]
  [143. 170. 125.]
  [178. 205. 162.]]

 [[ 72.  63. 116.]
  [ 75.  65. 118.]
  [ 84.  67. 122.]
  ...
  [144. 173. 119.]
  [139. 166. 121.]
  [175. 202. 159.]]

 [[ 77.  56. 115.]
  [ 85.  61. 121.]
  [ 99.  69. 131.]
  ...
  [141. 170. 116.]
  [137. 164. 119.]
  [173. 200. 157.]]

 ...

 [[100. 124.  76.]
  [ 98. 122.  74.]
  [ 96. 119.  75.]
  ...
  [ 39.  48.  45.]
  [ 40.  49.  46.]
  [ 42.  51.  48.]]

 [[ 96. 120.  72.]
  [ 96. 120.  72.]
  [ 94. 117.  73.]
  ...
  [ 41.  50.  45.]
  [ 43.  52.  47.]
  [ 44.  53.  48.]]

 [[102. 126.  78.]
  [101. 125.  77.]
  [100. 123.  79.]
  ...
  [ 41.  50.  45.]
  [ 43.  52.  47.]
  [ 45.  54.  49.]]]


In [5]:
img_array.shape

(214, 300, 3)

In [10]:
x = img_array.reshape((1,)+img_array.shape)
x.shape

(1, 214, 300, 3)

In [12]:
count = 0
for batch in datagen.flow(x, batch_size=5,save_to_dir="Augmented Data", save_prefix="img", save_format='jpeg' ):
    count +=1
    if count > 10:
        break